Rewrite in bash

diff --git a/window_manager/.config/sway/scripts/cpu_usage b/window_manager/.config/sway/scripts/cpu_usage
--- a/window_manager/.config/sway/scripts/cpu_usage
+++ b/window_manager/.config/sway/scripts/cpu_usage
@@ -1,62 +1,33 @@
-#!/usr/bin/perl
-#
-# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
-# Copyright 2014 Vivien Didelot <vivien@didelot.org>
-# Copyright 2014 Andreas Guldstrand <andreas.guldstrand@gmail.com>
-#
-# Licensed under the terms of the GNU GPL v3, or any later version.
+#!/usr/bin/env bash
 
-use strict;
-use warnings;
-use utf8;
-use Getopt::Long;
+# Thresholds from environment variables
+T_WARN="${T_WARN:-50}"
+T_CRIT="${T_CRIT:-80}"
+DECIMALS="${DECIMALS:-0}"
+LABEL="${LABEL:-}"
 
-# default values
-my $t_warn = $ENV{T_WARN} // 50;
-my $t_crit = $ENV{T_CRIT} // 80;
-my $cpu_usage = -1;
-my $decimals = $ENV{DECIMALS} // 0;
-my $label = $ENV{LABEL} // "";
+# Get CPU usage using mpstat
+LC_ALL="en_US"
+cpu_idle=$(LC_ALL="$LC_ALL" mpstat 1 1 | awk '/^Average:/ {print $NF}')
 
-sub help {
-    print "Usage: cpu_usage [-w <warning>] [-c <critical>] [-d <decimals>]\n";
-    print "-w <percent>: warning threshold to become yellow\n";
-    print "-c <percent>: critical threshold to become red\n";
-    print "-d <decimals>:  Use <decimals> decimals for percentage (default is $decimals) \n"; 
-    exit 0;
-}
+if [[ -z "$cpu_idle" ]]; then
+    echo "Can't find CPU information" >&2
+    exit 1
+fi
 
-GetOptions("help|h" => \&help,
-           "w=i"    => \$t_warn,
-           "c=i"    => \$t_crit,
-           "d=i"    => \$decimals,
-);
-
-# Get CPU usage
-$ENV{LC_ALL}="en_US"; # if mpstat is not run under en_US locale, things may break, so make sure it is
-open (MPSTAT, 'mpstat 1 1 |') or die;
-while (<MPSTAT>) {
-    if (/^.*\s+(\d+\.\d+)[\s\x00]?$/) {
-        $cpu_usage = 100 - $1; # 100% - %idle
-        last;
-    }
-}
-close(MPSTAT);
-
-$cpu_usage eq -1 and die 'Can\'t find CPU information';
+# Calculate CPU usage (100% - %idle)
+cpu_usage=$(awk "BEGIN {printf \"%.${DECIMALS}f\", 100 - $cpu_idle}")
 
 # Print short_text, full_text
-print "${label}";
-printf "%02.${decimals}f%%\n", $cpu_usage;
-print "${label}";
-printf "%02.${decimals}f%%\n", $cpu_usage;
+printf "%s%0${DECIMALS}.${DECIMALS}f%%\n" "$LABEL" "$cpu_usage"
+printf "%s%0${DECIMALS}.${DECIMALS}f%%\n" "$LABEL" "$cpu_usage"
 
 # Print color, if needed
-if ($cpu_usage >= $t_crit) {
-    print "#FF0000\n";
-    exit 33;
-} elsif ($cpu_usage >= $t_warn) {
-    print "#FFFC00\n";
-}
+cpu_int=${cpu_usage%.*}
+if ((cpu_int >= T_CRIT)); then
+    echo "#FF0000"
+elif ((cpu_int >= T_WARN)); then
+    echo "#FFFC00"
+fi
 
-exit 0;
+exit 0
diff --git a/window_manager/.config/sway/scripts/gpu_usage b/window_manager/.config/sway/scripts/gpu_usage
--- a/window_manager/.config/sway/scripts/gpu_usage
+++ b/window_manager/.config/sway/scripts/gpu_usage
@@ -1,87 +1,35 @@
-#!/usr/bin/env perl
+#!/usr/bin/env bash
 
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, either version 3 of the License, or
-# (at your option) any later version.
-
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-
-use strict;
-use warnings;
-use utf8;
-use Getopt::Long;
+# Thresholds from environment variables
+T_WARN="${T_WARN:-70}"
+T_CRIT="${T_CRIT:-90}"
 
 # default values
-my $t_warn = $ENV{T_WARN} || 70;
-my $t_crit = $ENV{T_CRIT} || 90;
-my $gpu_brand = $ENV{GPU_BRAND} || "AMD";
-my $gpu_usage = -1;
-my $gpu_mem = -1;
-my $gpu_video = -1;
-my $gpu_pcie = -1;
+gpu_usage=-1
+gpu_mem=-1
 
-my $full_text = "";
+# Get GPU usage from radeontop
+amd_info=$(radeontop -d - -l 1 2>/dev/null)
+if [[ "$amd_info" =~ gpu\ ([0-9]+)\.[0-9]+%.*vram\ ([0-9]+)\.[0-9]+% ]]; then
+    gpu_usage="${BASH_REMATCH[1]}"
+    gpu_mem="${BASH_REMATCH[2]}"
+fi
 
-sub help {
-    print "Usage: gpu-load [-w <warning>] [-c <critical>]\n";
-    print "-w <percent>: warning threshold to become amber\n";
-    print "-c <percent>: critical threshold to become red\n";
-    exit 0;
-}
-
-GetOptions("help|h" => \&help,
-           "w=i"    => \$t_warn,
-           "c=i"    => \$t_crit);
-
-# Get GPU usage from nvidia-settings
-if ($gpu_brand eq "NVIDIA") {
-    open (NVS, 'nvidia-settings -q GPUUtilization -t |') or die;
-    while (<NVS>) {
-        if (/^[a-zA-Z]*=(\d+), [a-zA-Z]*=(\d+), [a-zA-Z]*=(\d+), [a-zA-Z]*=(\d+)$/) {
-            $gpu_usage = $1;
-            $gpu_mem = $2;
-            $gpu_video = $3;
-            $gpu_pcie = $4;
-            last;
-        }
-    }
-    close(NVS);
-    $full_text = sprintf "%.0f%% %.0f%% %.0f%% %.0f%%\n", $gpu_usage, $gpu_mem, $gpu_video, $gpu_pcie;
-}
-
-# For AMD, get from radeontop
-elsif ($gpu_brand eq "AMD") {
-    open (AMD, 'radeontop -d - -l 1 |') or die;
-    while (<AMD>) {
-        if (/gpu (\d+)\.\d+%.*vram (\d+)\.\d+%/) {
-            $gpu_usage = $1;
-            $gpu_mem = $2;
-            last;
-        }
-    }
-    close(AMD);
-    $full_text = sprintf "%.0f%% %.0f%%\n", $gpu_usage, $gpu_mem;
-}
-
-$gpu_usage eq -1 and die 'Can\'t find GPU information';
+if [[ "$gpu_usage" == -1 ]]; then
+    echo "Can't find GPU information" >&2
+    exit 1
+fi
 
 # Print full_text, short_text
-print $full_text;
-printf "%.0f%%\n", $gpu_usage;
+full_text=$(printf "%.0f%% %.0f%%\n" "$gpu_usage" "$gpu_mem")
+echo "$full_text"
+printf "%.0f%%\n" "$gpu_usage"
 
 # Print color, if needed
-if ($gpu_usage >= $t_crit || $gpu_mem >= $t_crit || $gpu_video >= $t_crit || $gpu_pcie >= $t_crit) {
-    print "#FF0000\n";
-    exit 33;
-} elsif ($gpu_usage >= $t_warn || $gpu_mem >= $t_warn || $gpu_video >= $t_warn || $gpu_pcie >= $t_warn) {
-    print "#FFBF00\n";
-}
+if ((gpu_usage >= T_CRIT || gpu_mem >= T_CRIT)); then
+    echo "#FF0000"
+elif ((gpu_usage >= T_WARN || gpu_mem >= T_WARN)); then
+    echo "#FFBF00"
+fi
 
-exit 0;
+exit 0
