Add and update powermenu script

diff --git a/window_manager/.config/sway/scripts/powermenu b/window_manager/.config/sway/scripts/powermenu
--- a/window_manager/.config/sway/scripts/powermenu
+++ b/window_manager/.config/sway/scripts/powermenu
@@ -1,8 +1,6 @@
 #!/usr/bin/env bash
 #
-# Use rofi/zenity to change system runstate thanks to systemd.
-#
-# Note: this currently relies on associative array support in the shell.
+# Use yad to change system runstate thanks to systemd.
 #
 # Inspired from i3pystatus wiki:
 # https://github.com/enkore/i3pystatus/wiki/Shutdown-Menu
@@ -14,36 +12,17 @@
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-
-# modified to work with latest rofi update by joekamprad <joekamprad@endeavouros.com>
+# Modified to use yad instead of rofi/zenity
 
 #######################################################################
 #                            BEGIN CONFIG                             #
 #######################################################################
 
-# Use a custom lock script
-#LOCKSCRIPT="i3lock-extra -m pixelize"
-
-# Colors: FG (foreground), BG (background), HL (highlighted)
-FG_COLOR="#bbbbbb"
-BG_COLOR="#111111"
-HLFG_COLOR="#111111"
-HLBG_COLOR="#bbbbbb"
-BORDER_COLOR="#222222"
-
-# Options not related to colors (most rofi options do not work anymore)
-ROFI_OPTIONS=(-theme ~/.config/rofi/powermenu.rasi)
-# Zenity options
-ZENITY_TITLE="Power Menu"
-ZENITY_TEXT="Action:"
-ZENITY_OPTIONS=(--column= --hide-header)
+# Yad options
+YAD_TITLE="Power Menu"
+YAD_WIDTH=200
+YAD_HEIGHT=200
+YAD_OPTIONS=(--fixed --on-top --center --skip-taskbar)
 
 #######################################################################
 #                             END CONFIG                              #
@@ -52,46 +31,24 @@ ZENITY_OPTIONS=(--column= --hide-header)
 # Whether to ask for user's confirmation
 enable_confirmation=false
 
-# Preferred launcher if both are available
-preferred_launcher="rofi"
-
-usage="$(basename "$0") [-h] [-c] [-p name] -- display a menu for shutdown, reboot, lock etc.
+usage="$(basename "$0") [-h] [-c] -- display a menu for shutdown, reboot, lock etc.
 
 where:
     -h  show this help text
     -c  ask for user confirmation
-    -p  preferred launcher (rofi or zenity)
 
 This script depends on:
   - systemd,
-  - i3,
-  - rofi or zenity."
-
-# Check whether the user-defined launcher is valid
-launcher_list=(rofi zenity)
-function check_launcher() {
-  if [[ ! "${launcher_list[@]}" =~ (^|[[:space:]])"$1"($|[[:space:]]) ]]; then
-    echo "Supported launchers: ${launcher_list[*]}"
-    exit 1
-  else
-    # Get array with unique elements and preferred launcher first
-    # Note: uniq expects a sorted list, so we cannot use it
-    i=1
-    launcher_list=($(for l in "$1" "${launcher_list[@]}"; do printf "%i %s\n" "$i" "$l"; let i+=1; done \
-      | sort -uk2 | sort -nk1 | cut -d' ' -f2- | tr '\n' ' '))
-  fi
-}
+  - sway/i3,
+  - yad."
 
 # Parse CLI arguments
-while getopts "hcp:" option; do
+while getopts "hc" option; do
   case "${option}" in
     h) echo "${usage}"
        exit 0
        ;;
     c) enable_confirmation=true
-       ;;
-    p) preferred_launcher="${OPTARG}"
-       check_launcher "${preferred_launcher}"
        ;;
     *) exit 1
        ;;
@@ -108,79 +65,68 @@ if ! command_exists systemctl ; then
   exit 1
 fi
 
-# menu defined as an associative array
-typeset -A menu
-
-# Menu with keys/commands
-
-menu=(
-  [ Shutdown]="systemctl poweroff"
-  [ Reboot]="systemctl reboot"
-  [ Suspend]="systemctl suspend"
-  [ Hibernate]="systemctl hibernate"
-  [ Lock]="~/.config/i3/scripts/blur-lock"
-  [ Logout]="i3-msg exit"
-  [ Cancel]=""
-)
-
-menu_nrows=${#menu[@]}
-
-# Menu entries that may trigger a confirmation message
-menu_confirm="Shutdown Reboot Hibernate Suspend Halt Logout"
-
-launcher_exe=""
-launcher_options=""
-rofi_colors=""
-
-function prepare_launcher() {
-  if [[ "$1" == "rofi" ]]; then
-    rofi_colors=(-bc "${BORDER_COLOR}" -bg "${BG_COLOR}" -fg "${FG_COLOR}" \
-        -hlfg "${HLFG_COLOR}" -hlbg "${HLBG_COLOR}")
-    launcher_exe="rofi"
-    launcher_options=(-dmenu -i -lines "${menu_nrows}" -p "${ROFI_TEXT}" \
-        "${rofi_colors}" "${ROFI_OPTIONS[@]}")
-  elif [[ "$1" == "zenity" ]]; then
-    launcher_exe="zenity"
-    launcher_options=(--list --title="${ZENITY_TITLE}" --text="${ZENITY_TEXT}" \
-        "${ZENITY_OPTIONS[@]}")
-  fi
-}
-
-for l in "${launcher_list[@]}"; do
-  if command_exists "${l}" ; then
-    prepare_launcher "${l}"
-    break
-  fi
-done
-
-# No launcher available
-if [[ -z "${launcher_exe}" ]]; then
+# yad required
+if ! command_exists yad ; then
+  echo "Error: yad is required but not installed."
   exit 1
 fi
 
-launcher=(${launcher_exe} "${launcher_options[@]}")
-selection="$(printf '%s\n' "${!menu[@]}" | sort | "${launcher[@]}")"
+# Menu items with their commands
+declare -A menu
+menu[" Shutdown"]="systemctl poweroff"
+menu[" Reboot"]="systemctl reboot"
+menu[" Suspend"]="systemctl suspend"
+menu[" Hibernate"]="systemctl hibernate"
+menu[" Lock"]="~/.config/sway/scripts/blur-lock"
+menu[" Logout"]="swaymsg exit"
 
+# Order of items in the list (top to bottom)
+menu_items=("  Lock" "  Logout" "  Suspend" "  Hibernate" "  Reboot" "  Shutdown")
+
+# Menu entries that may trigger a confirmation message
+menu_confirm="Shutdown Reboot Hibernate Suspend Logout"
+
+# Build menu list for yad
+menu_list=""
+for item in "${menu_items[@]}"; do
+  menu_list+="${item}"$'\n'
+done
+
+# Display menu using yad list mode
+selection=$(printf '%s' "$menu_list" | yad --list \
+  --title="${YAD_TITLE}" \
+  --width="${YAD_WIDTH}" \
+  --height="${YAD_HEIGHT}" \
+  --column="" \
+  --hide-header \
+  --no-headers \
+  "${YAD_OPTIONS[@]}")
+
+# Exit if no selection or Cancel was chosen
+if [[ -z "${selection}" || "${selection}" == "Cancel" ]]; then
+  exit 0
+fi
+
+# Confirm dangerous actions
 function ask_confirmation() {
-  if [ "${launcher_exe}" == "rofi" ]; then
-    confirmed=$(echo -e "Yes\nNo" | rofi -dmenu -i -lines 2 -p "${selection}?" \
-      "${rofi_colors}" "${ROFI_OPTIONS[@]}")
-    [ "${confirmed}" == "Yes" ] && confirmed=0
-  elif [ "${launcher_exe}" == "zenity" ]; then
-    zenity --question --text "Are you sure you want to ${selection,,}?"
-    confirmed=$?
-  fi
-
-  if [ "${confirmed}" == 0 ]; then
-    i3-msg -q "exec --no-startup-id ${menu[${selection}]}"
-  fi
+  # Strip icon from selection for display
+  local action_name="${selection#* }"
+  yad --question \
+    --title="Confirm" \
+    --text="Are you sure you want to ${action_name}?" \
+    --button=Yes:0 \
+    --button=No:1 \
+    "${YAD_OPTIONS[@]}"
+  return $?
 }
 
-if [[ $? -eq 0 && ! -z ${selection} ]]; then
-  if [[ "${enable_confirmation}" = true && \
-        ${menu_confirm} =~ (^|[[:space:]])"${selection}"($|[[:space:]]) ]]; then
-    ask_confirmation
+# Execute the action
+if [[ -n "${menu[${selection}]}" ]]; then
+  if [[ "${enable_confirmation}" = true && "${menu_confirm}" =~ (^|[[:space:]])"${selection}"($|[[:space:]]) ]]; then
+    if ask_confirmation; then
+      swaymsg -q "exec --no-startup-id ${menu[${selection}]}"
+    fi
   else
-    i3-msg -q "exec --no-startup-id ${menu[${selection}]}"
+    swaymsg -q "exec --no-startup-id ${menu[${selection}]}"
   fi
 fi
